-- Users - main table
CREATE TABLE IF NOT EXISTS Users (
    UserId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username varchar(32) NOT NULL UNIQUE,
    PasswordHash varchar(255) NOT NULL
);

-- LostItems
-- CreatorId is the UserId of person creating request
CREATE TABLE IF NOT EXISTS LostItems (
    ItemId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CreatorId INT NOT NULL REFERENCES Users(UserId),
    ItemName varchar(255) NOT NULL,
    ItemDescription text,
    CreationDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EventDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ImageUrl text,
    Completed boolean NOT NULL DEFAULT FALSE,
    HelperId INT REFERENCES Users(UserId),
    Latitude DECIMAL(10, 7) CHECK (latitude BETWEEN -91.0000000 AND 91.0000000),
    Longitude DECIMAL(11, 7) CHECK (longitude BETWEEN -181.0000000 AND 181.0000000)
);

-- FoundItems
-- CreatorId is the UserId of person creating request
CREATE TABLE IF NOT EXISTS FoundItems (
    ItemId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CreatorId INT NOT NULL REFERENCES Users(UserId),
    ItemName varchar(255) NOT NULL,
    ItemDescription text,
    CreationDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EventDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ImageUrl text,
    Completed boolean NOT NULL DEFAULT FALSE,
    HelperId INT REFERENCES Users(UserId),
    Latitude DECIMAL(10, 7) CHECK (latitude BETWEEN -91.0000000 AND 91.0000000),
    Longitude DECIMAL(11, 7) CHECK (longitude BETWEEN -181.0000000 AND 181.0000000)
);

