-- Users - main table
CREATE TABLE IF NOT EXISTS Users (
    UserId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username varchar(32) NOT NULL UNIQUE,
    PasswordHash varchar(255) NOT NULL
);



-- example from other project
CREATE TABLE IF NOT EXISTS Run (
    id INT NOT NULL,
    title varchar(250) NOT NULL,
    started_on timestamp NOT NULL,
    completed_on timestamp NOT NULL,
    miles INT NOT NULL,
    location varchar(10) NOT NULL,
    version INT,
    PRIMARY KEY (id)
);
